✨ update to pkgs.k8s.io
syself/cluster-api-provider-hetzner pull request #1015
Opened 2023-10-20 13:16 UTC by kranurag7

this commit updates deps from apt.kuberentes.io to pkgs.k8s.io

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [x] squash commits
- [ ] include documentation
- [ ] add unit tests

2023-10-20 14:41 UTC, batistein requested changes

2023-10-20 14:41 UTC, batistein commented on templates/cluster-templates/bases/hcloud-kcp-ubuntu.yaml
>        - apt-get install -y kubelet=$KUBERNETES_VERSION-00 kubeadm=$KUBERNETES_VERSION-00 kubectl=$KUBERNETES_VERSION-00  bash-completion && apt-mark hold kubelet kubectl kubeadm && systemctl enable k
this needs to be changed to -1.1 in all files

2023-10-24 07:46 UTC, batistein requested changes

2023-12-06 11:56 UTC, guettli commented
Thank you Anurag for this PR.

We will upgrade to 1.28

New PR: https://github.com/syself/cluster-api-provider-hetzner/pull/1073

2023-12-06 11:56 UTC, closed without merging