🌱 Update hcloudmachine_types.go
syself/cluster-api-provider-hetzner pull request #1169
Opened 2024-02-19 05:29 UTC by Sayanta66

**What this PR does / why we need it**:

Added descriptions

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [x] include documentation
- [ ] add unit tests

2024-02-19 09:51 UTC, janiskemper requested changes

2024-02-19 09:51 UTC, janiskemper commented on api/v1beta1/hcloudmachine_types.go
> +	// The placement group of the machine in HCloud API must be referencing an existing placement group
```suggestion
	// The placement group of the machine in HCloud API must be referencing an existing placement group.
```

2024-02-19 11:48 UTC, janiskemper commented
thanks, you can squash

2024-02-19 12:33 UTC, Sayanta66 commented
Updating a few more descriptions in line with our reference docs. Then will squash all the commits together.

2024-02-19 13:37 UTC, janiskemper requested changes

2024-02-19 13:37 UTC, janiskemper commented on api/v1beta1/hcloudmachine_types.go
> +	// Define Machine specific SSH keys, and override cluster-wide SSH keys.
Start with "SSHKeys ..."

2024-02-21 11:07 UTC, janiskemper requested changes

2024-02-21 11:07 UTC, janiskemper commented on api/v1beta1/hcloudmachine_types.go
> +	// The placement group of the machine in HCloud API must be referencing an existing placement group.
Start with PlacementGroupName

2024-02-21 11:07 UTC, janiskemper commented on api/v1beta1/hcloudmachine_types.go
> +	// PublicNetwork specifies information for public networks.
this line and the following line don't fit together

2024-02-21 15:29 UTC, janiskemper requested changes

2024-02-21 15:29 UTC, janiskemper commented on api/v1beta1/hcloudmachine_types.go
> +	// ImageName can reference an image uploaded to Hetzner API in two ways: either directly as the name of an image or as the label of an image.
you don't need to start twice with "ImageName". Start with "it" or something

2024-02-21 15:29 UTC, janiskemper commented on api/v1beta1/hcloudmachine_types.go
> +	// SSHKeys define Machine-specific SSH keys and override cluster-wide SSH keys.
Machine -> machine

2024-02-27 07:57 UTC, janiskemper requested changes
there is an empty introduction.md file in this commit! You should remove it

2024-02-27 08:45 UTC, Sayanta66 commented
> there is an empty introduction.md file in this commit! You should remove it

Done

2024-02-27 09:12 UTC, janiskemper approved these changes

2024-02-27 10:46 UTC, merged