🌱 Update types.go
syself/cluster-api-provider-hetzner pull request #1170
Opened 2024-02-19 11:10 UTC by Sayanta66

**What this PR does / why we need it**:

Added spec description and fixes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [x] include documentation
- [ ] add unit tests

2024-02-19 11:47 UTC, janiskemper requested changes
always start comments with the name of the property. For example
"EnableIPv4 ...."

2024-02-21 11:05 UTC, janiskemper requested changes

2024-02-21 11:05 UTC, janiskemper commented on api/v1beta1/types.go
> +	// API Server port. It must be a valid ports range (1-65535). If omitted, the default value is 6443.
start with Port

2024-02-28 11:20 UTC, janiskemper requested changes

2024-02-29 04:49 UTC, Sayanta66 commented on api/v1beta1/types.go
> +	// Note: A subnet is required.
What do you mean by this?

2024-02-29 08:44 UTC, janiskemper commented on api/v1beta1/types.go
> +	// Note: A subnet is required.
there is a default value that is used usually! you can mention this, as you did in other cases as well

2024-04-04 11:04 UTC, janiskemper approved these changes

2024-04-04 11:32 UTC, merged