🌱 Update hetznerbaremetalhost_types.go
syself/cluster-api-provider-hetzner pull request #1172
Opened 2024-02-20 08:25 UTC by Sayanta66

**What this PR does / why we need it**:

Added spec descriptions and fixes.

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [x] include documentation
- [ ] add unit tests

2024-02-20 10:01 UTC, janiskemper requested changes

2024-02-20 10:01 UTC, janiskemper commented on api/v1beta1/hetznerbaremetalhost_types.go
> +	// To specify multiple storage devices. It provides the controller with information
you have to start with "Raid"

2024-02-21 15:24 UTC, janiskemper requested changes

2024-02-21 15:24 UTC, janiskemper commented on api/v1beta1/hetznerbaremetalhost_types.go
> +	// WWN defines a list of Unique storage identifiers used for raid setups.
Unique -> unique

2024-02-29 08:42 UTC, janiskemper commented on api/v1beta1/hetznerbaremetalhost_types.go
> +	// WWN defines a list of Unique storage identifiers used for raid setups.
this is not resolved

2024-02-29 13:44 UTC, janiskemper commented on api/v1beta1/hetznerbaremetalhost_types.go
> +	// WWN defines a list of Unique storage identifiers used for raid setups.
not solved

2024-03-27 20:01 UTC, kranurag7 submitted a review, later dismissed

2024-03-28 07:58 UTC, janiskemper commented on api/v1beta1/hetznerbaremetalhost_types.go
> +// ProvisioningState defines the states the provisioner will report the host was having.
```suggestion
// ProvisioningState defines the states of provisioning of the host.
```

2024-03-28 13:51 UTC, merged