🌱 update CAPH upgrade docs
syself/cluster-api-provider-hetzner pull request #1263
Opened 2024-04-11 15:26 UTC by kranurag7

update upgrade guide with v1.6.0 and v1.6.3 and some rephrasing as well.

2024-04-15 11:34 UTC, janiskemper requested changes

2024-04-15 11:34 UTC, janiskemper commented on docs/topics/upgrade.md
> +After upgrading cluster API, you might be intersted in updating the Kubernetes version of your controlplane and worker nodes. Those details can be found in the [Cluster API documentation](https://clu
can you add this link to the beginning and specify what we show in this document and what is shown in CAPI's docs?

2024-05-08 10:30 UTC, janiskemper reviewed
LGTM from my side.

2024-05-08 11:08 UTC, guettli approved these changes
lgtm

2024-05-08 13:36 UTC, merged