:seedling: Always create a Condition, if createServer failed (hcloud)
syself/cluster-api-provider-hetzner pull request #1428
Opened 2024-08-09 07:16 UTC by guettli

**What this PR does / why we need it**:

If this error happens (events):

![image](https://github.com/user-attachments/assets/c33c089b-82d9-493e-a8c0-8be001575f4d)

Up to now, no Condition gets set:

![image](https://github.com/user-attachments/assets/008773ba-cbc4-4f32-b9c4-f0e1d249d6b4)

This PR updates to code, so that always a Condition get set (if createServer failed)

2024-08-09 13:13 UTC, janiskemper requested changes
this is related to https://github.com/syself/cluster-api-provider-hetzner/issues/1414. Please consider that issue description

2024-08-09 13:51 UTC, guettli commented on controllers/hetznerbaremetalremediation_controller_test.go
> +				It("should not remediate if no annotations is present in the hetznerBaremetalMachine (flaky)", func() {
@janiskemper 
 This test was flaky, so I marked it accordingly

2024-08-09 13:53 UTC, guettli commented
> this is related to #1414. Please consider that issue description

nice, this makes it simpler. I updated the PR.

2024-08-10 13:21 UTC, janiskemper approved these changes

2024-08-10 14:17 UTC, merged