:seedling: more complete .envrc.sample file.
syself/cluster-api-provider-hetzner pull request #847
Opened 2023-07-11 09:01 UTC by guettli

**What this PR does / why we need it**:

this PR extends the .envrc.sample file and adds a check for env vars in the makefile targets "create-workload-....".

2023-07-11 20:15 UTC, batistein requested changes

2023-07-11 20:15 UTC, batistein commented on .envrc.sample
> +export HETZNER_SSH_PUB_PATH=$HOME/.ssh/test-sponsoring.pub
please change the name of the ssh key

2023-07-12 06:35 UTC, janiskemper submitted a review, later dismissed

2023-07-14 08:52 UTC, batistein submitted a review, later dismissed

2023-07-14 10:43 UTC, batistein requested changes

2023-07-14 10:43 UTC, batistein commented on hack/ci-e2e-get-token.sh
> +    echo "New HCLOUD_TOKEN: $token"
This breaks the CI - please revert

2023-07-14 11:27 UTC, guettli commented on hack/ci-e2e-get-token.sh
> +    echo "New HCLOUD_TOKEN: $token"
I am sorry. I have fixed it.

2023-07-14 12:17 UTC, merged