🐛Don't reboot if HetzerBareMetalMachine not found
syself/cluster-api-provider-hetzner pull request #927
Opened 2023-09-20 06:02 UTC by aniruddha2000

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

2023-09-20 06:31 UTC, janiskemper requested changes
can you also return in line 79? I think we did a mistake there to not return after manipulating the machine

2023-09-20 06:31 UTC, janiskemper commented on pkg/services/baremetal/remediation/remediation.go
> +				return res, err
you don't want to return an error in this case I guess. You did an action (-> manipulated the machine object) and that's as expected.

2023-09-21 07:36 UTC, janiskemper requested changes

2023-09-21 07:36 UTC, janiskemper commented on pkg/services/baremetal/remediation/remediation.go
> -			return res, err
I think there was a misunderstanding.. I said do not return an error, not do not return at all :D Please keep the return here!

2023-09-21 07:36 UTC, janiskemper commented on pkg/services/baremetal/remediation/remediation.go
> -				return res, err
I actually think that here we should still return an error even, as this error that we couldn't update the Machine object is unexpected

2023-09-21 09:35 UTC, janiskemper approved these changes

2023-09-21 12:07 UTC, merged

2023-09-21 12:16 UTC, aniruddha2000 commented
yes