:bug: Fix robot log and switch to pflag
syself/cluster-api-provider-hetzner pull request #991
Opened 2023-09-29 12:37 UTC by janiskemper

**What this PR does / why we need it**:
Fix logger of robot api and switch to pflag package

**TODOs**:
- [x] squash commits
- [ ] include documentation
- [ ] add unit tests

2023-09-29 12:42 UTC, batistein requested changes

2023-09-29 12:42 UTC, batistein commented on Tiltfile
> +            "--log-level=info",
i think this should be debug

2023-09-30 07:48 UTC, batistein approved these changes

2023-09-30 07:57 UTC, merged

2023-10-05 06:42 UTC, apricote commented
Just FYI, this caused my existing deployment to fail after updating the image because one flag i was using had a single hyphen (`-metrics-bind-address`) and this was no longer allowed.

---

OT: It would be very nice if CAPH supported the same flags as other CAPI components, to make using it with the capi-operator nicer. In this case, the capi-operator expects the flag [`--metrics-bind-addr`](https://github.com/kubernetes-sigs/cluster-api-operator/blob/cf9a1ae3cc1a878cb94bb3d0b396c255379a971c/internal/controller/component_customizer.go#L193-L195) instead of CAPHs `--metrics-bind-address`. Because of this I need to add the flag manually instead of using the field provided in the `InfrastructureManager` CR.

I will open an issue for this when I find the time.

2023-10-05 08:59 UTC, janiskemper commented
then you were smarter than us, because we realized that our example deployments did it wrongly and the flags did not take effect (they were not changing anything really, that's why we also didn't realize).

I guess your proposed change makes sense. AFAIK we should be mostly aligned with other providers though.

@batistein can we document this change somewhere in case other people run into this?