test for server image list condition
syself/cluster-api-provider-hetzner pull request #996
Opened 2023-10-04 07:50 UTC by aniruddha2000

**What this PR does / why we need it**:

**Which issue(s) this PR fixes** *(optional, in `fixes #<issue number>(, fixes #<issue_number>, ...)` format, will close the issue(s) when PR gets merged)*:
Fixes #943 

**Special notes for your reviewer**:

_Please confirm that if this PR changes any image versions, then that's the sole change this PR makes._

**TODOs**:

- [ ] squash commits
- [ ] include documentation
- [ ] add unit tests

2023-10-04 10:58 UTC, janiskemper reviewed
what happened to these tests that have to manually set the bootstrap condition? Why did you change something here?

2023-10-04 11:01 UTC, aniruddha2000 commented on controllers/hcloudmachine_controller_test.go
> +		Context("correct server", func() {
change the name

2023-10-04 19:46 UTC, janiskemper requested changes

2023-10-04 19:46 UTC, janiskemper commented on controllers/hcloudmachine_controller_test.go
> +			It("checks for ServerCreateSucceededCondition of hcloudMachine object", func() {
It checks that ImageNotFound is visible in conditions if image does not exist

2023-10-04 19:46 UTC, janiskemper commented on pkg/services/hcloud/server/server.go
> +	s.scope.Logger.Info("lenth of image", "len", len(images), "imagesByName", len(imagesByName), "actual name", s.scope.HCloudMachine.Spec.ImageName)
rm

2023-10-05 09:03 UTC, janiskemper approved these changes

2023-10-14 19:14 UTC, merged